env:
    browser: true
    es2021: true
extends:
    - airbnb-base/legacy
    - prettier
parserOptions:
    ecmaVersion: latest
    sourceType: module
rules: { no-console: 0, indent: ['error', 4, { 'SwitchCase': 1 }] }
